name: methane
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - earthengine-api
  - geemap
  - jupyter
  - numpy
  - pre-commit
  - ruff
  - pytest
  - xarray
  - scipy
  - netcdf4

  - pip:
      - hitran-api            # the HAPI wrapper you need
