name: methane
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - earthengine-api
  - geemap
  - jupyter
  - numpy
  - ipywidgets
  - pre-commit
  - ruff
  - pytest
  - lxml
  - python-dotenv
  - pyproj
  - shapely
  - affine
  - rasterio
  - scipy
  - localtileserver
